#swiftmailer:
#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }

swiftmailer:
    transport: gmail
    auth_mode: login
    port: 465
    host: smtp.gmail.com
    username: 'no-reply@agence-inspire.com'
    password: 'NoReply232006'
    spool: { type: 'memory' }
